version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-template-node:
    build:
      target: development
    image: ffc-template-node-development
    command: npm run test
    volumes:
      - ./test-output/:/home/node/test-output/
