{{- include "ffc-helm-library.container-secret" (list . "ffc-template-node.container-secret") -}}
{{- define "ffc-template-node.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
{{- end -}}
